import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { Eye, MoreHorizontal, Plus, Search, UserRoundPlus } from 'lucide-react';
import { api, date, money } from '../api';
import type { Benefit, Member, Plan } from '../types';
import { Button, Empty, ErrorState, Field, Loading, Modal, Status, ToastView } from '../components';

export default function Members() {
  const [members, setMembers] = useState<Member[]>(); const [plans, setPlans] = useState<Plan[]>([]); const [benefits, setBenefits] = useState<Benefit[]>([]);
  const [query, setQuery] = useState(''); const [modal, setModal] = useState<'new' | 'detail' | null>(null); const [selected, setSelected] = useState<Member>();
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [toast, setToast] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const load = useCallback(async () => { try { setError(''); const [m, p, b] = await Promise.all([api<Member[]>('/members'), api<Plan[]>('/plans?onlyActive=true'), api<Benefit[]>('/benefits')]); setMembers(m.data); setPlans(p.data); setBenefits(b.data); } catch (e) { setError(e instanceof Error ? e.message : 'Error'); } }, []);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => (members || []).filter(m => `${m.firstName} ${m.lastName} ${m.dni} ${m.email || ''}`.toLowerCase().includes(query.toLowerCase())), [members, query]);
  async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setSaving(true); const f = new FormData(e.currentTarget); const body = Object.fromEntries(f); if (!body.email) delete body.email; if (!body.birthDate) delete body.birthDate; if (!body.benefitId) delete body.benefitId; try { await api('/members', { method: 'POST', body: JSON.stringify(body) }); setModal(null); setToast({ type: 'success', message: 'Socio registrado y primer pago generado.' }); load(); } catch (e) { setToast({ type: 'error', message: e instanceof Error ? e.message : 'No se pudo registrar' }); } finally { setSaving(false); } }
  async function detail(m: Member) { setSelected(m); setModal('detail'); try { const r = await api<Member>(`/members/${m.id}`); setSelected(r.data); } catch { /* muestra datos de lista */ } }
  async function toggle(m: Member) { try { await api(`/members/${m.id}/${m.status === 'ACTIVE' ? 'deactivate' : 'activate'}`, { method: 'PATCH' }); setModal(null); setToast({ type: 'success', message: m.status === 'ACTIVE' ? 'Socio dado de baja.' : 'Socio reactivado.' }); load(); } catch (e) { setToast({ type: 'error', message: e instanceof Error ? e.message : 'No se pudo actualizar' }); } }
  if (error) return <ErrorState message={error} retry={load} />; if (!members) return <Loading />;
  return <div className="stack"><ToastView toast={toast} clear={() => setToast(null)} />
    <div className="toolbar"><div className="search"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar por nombre, DNI o email…" /></div><Button icon={<Plus />} onClick={() => setModal('new')}>Nuevo socio</Button></div>
    <div className="mini-stats"><span><b>{members.length}</b> socios activos</span><span><b>{members.filter(m => m.benefits.some(b => b.active)).length}</b> con beneficio</span><span><b>{members.filter(m => !m.payments[0] || new Date(m.payments[0].expirationDate) < new Date()).length}</b> vencidos</span></div>
    <div className="card table-card"><div className="table-scroll"><table><thead><tr><th>Socio</th><th>DNI / contacto</th><th>Plan actual</th><th>Beneficio</th><th>Vencimiento</th><th>Estado</th><th /></tr></thead><tbody>{filtered.map(m => { const payment = m.payments[0]; const paid = !!payment && new Date(payment.expirationDate) > new Date() && payment.status === 'PAID'; const benefit = m.benefits.find(b => b.active)?.benefit; return <tr key={m.id}><td data-label="Socio"><div className="person"><div className="avatar small">{m.firstName[0]}{m.lastName[0]}</div><div><b>{m.firstName} {m.lastName}</b><span>Desde {date(m.enrollmentDate)}</span></div></div></td><td data-label="DNI / contacto"><b>{m.dni}</b><small>{m.phone}</small></td><td data-label="Plan actual">{payment?.plan.name || 'Sin plan'}{payment && <small>{money(payment.finalAmount)}</small>}</td><td data-label="Beneficio">{benefit ? <span className="tag lime">{benefit.name}</span> : <span className="muted">Sin beneficio</span>}</td><td data-label="Vencimiento">{date(payment?.expirationDate)}</td><td data-label="Estado"><Status ok={paid}>{paid ? 'Al día' : 'Vencido'}</Status></td><td data-label="Acciones"><button className="icon-btn" onClick={() => detail(m)} title="Ver detalle"><MoreHorizontal /></button></td></tr>; })}</tbody></table></div>{!filtered.length && <Empty title="No encontramos socios" text="Probá con otra búsqueda o registrá uno nuevo." />}</div>
    {modal === 'new' && <Modal title="Registrar nuevo socio" subtitle="El alta genera automáticamente el primer pago por 30 días." onClose={() => setModal(null)} wide><form onSubmit={create}><div className="form-grid"><Field label="Nombre *"><input name="firstName" minLength={2} required /></Field><Field label="Apellido *"><input name="lastName" minLength={2} required /></Field><Field label="DNI *"><input name="dni" inputMode="numeric" pattern="[0-9]{7,8}" required /></Field><Field label="Teléfono *"><input name="phone" placeholder="3446 123456" minLength={8} required /></Field><Field label="Email"><input name="email" type="email" /></Field><Field label="Fecha de nacimiento"><input name="birthDate" type="date" /></Field><Field label="Plan *"><select name="planId" required defaultValue=""><option value="" disabled>Seleccionar plan</option>{plans.map(p => <option key={p.id} value={p.id}>{p.name} — {money(p.price)}</option>)}</select></Field><Field label="Beneficio"><select name="benefitId" defaultValue=""><option value="">Sin beneficio</option>{benefits.map(b => <option key={b.id} value={b.id}>{b.name} ({b.discountPercentage}%){b.onlyFullPass ? ' · Full Pass' : ''}</option>)}</select></Field><Field label="Forma de pago *"><select name="paymentMethod"><option value="CASH">Efectivo</option><option value="TRANSFER">Transferencia</option></select></Field><Field label="Notas"><input name="notes" placeholder="Información adicional" /></Field></div><div className="form-note"><UserRoundPlus /> Los beneficios no son acumulables. Verificá el plan antes de registrar al socio.</div><div className="modal-actions"><Button type="button" variant="ghost" onClick={() => setModal(null)}>Cancelar</Button><Button disabled={saving}>{saving ? 'Registrando…' : 'Registrar socio'}</Button></div></form></Modal>}
    {modal === 'detail' && selected && <Modal title={`${selected.firstName} ${selected.lastName}`} subtitle={`DNI ${selected.dni}`} onClose={() => setModal(null)} wide><div className="detail-grid"><div><span>Teléfono</span><b>{selected.phone}</b></div><div><span>Email</span><b>{selected.email || '—'}</b></div><div><span>Alta</span><b>{date(selected.enrollmentDate)}</b></div><div><span>Estado</span><Status ok={selected.status === 'ACTIVE'}>{selected.status === 'ACTIVE' ? 'Activo' : 'Inactivo'}</Status></div></div><h4 className="section-title">Historial de pagos</h4>{selected.payments?.length ? <div className="compact-list">{selected.payments.map(p => <div key={p.id}><div><b>{p.plan.name}</b><span>{date(p.paymentDate)} · {p.paymentMethod === 'CASH' ? 'Efectivo' : 'Transferencia'}</span></div><strong>{money(p.finalAmount)}</strong></div>)}</div> : <Empty title="Sin pagos" /> }<div className="modal-actions"><Button variant={selected.status === 'ACTIVE' ? 'danger' : 'secondary'} onClick={() => toggle(selected)}>{selected.status === 'ACTIVE' ? 'Dar de baja' : 'Reactivar socio'}</Button><Button variant="ghost" onClick={() => setModal(null)}>Cerrar</Button></div></Modal>}
  </div>;
}
