import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { AlertCircle, CalendarClock, CheckCircle2, Plus, Search } from 'lucide-react';
import { useAuth } from '../AuthContext';
import { api, date, money } from '../api';
import { PaymentFields } from '../payment-fields';
import { inputDate, paymentMethodLabel, memberExpiration } from '../payment-utils';
import type { Benefit, Member, Payment, Plan } from '../types';
import { Button, Empty, ErrorState, Field, Loading, Modal, Status, ToastView } from '../components';

export default function Payments() {
  const {user} = useAuth(); const isAdmin = user?.role.name === 'ADMIN';
  const [benefits,setBenefits]=useState<Benefit[]>([]); const [paymentBenefit,setPaymentBenefit]=useState(''); const [paymentAmount,setPaymentAmount]=useState(''); const [paymentExpiry,setPaymentExpiry]=useState('');
  const [deleting, setDeleting] = useState<Payment>();
  const [notRenewed, setNotRenewed] = useState<Member[]>([]); const [month, setMonth] = useState(inputDate().slice(0,7));
  const [editing, setEditing] = useState<Payment>(); const [selectedPlan, setSelectedPlan] = useState('');
  const [payments, setPayments] = useState<Payment[]>(); const [overdue, setOverdue] = useState<Member[]>([]); const [upcoming, setUpcoming] = useState<Payment[]>([]); const [members, setMembers] = useState<Member[]>([]); const [plans, setPlans] = useState<Plan[]>([]);
  const [tab, setTab] = useState<'all' | 'overdue' | 'upcoming' | 'notRenewed' | 'imported'>('all'); const [query, setQuery] = useState(''); const [modal, setModal] = useState<'payment' | 'renew' | 'expiration' | 'delete' | null>(null); const [renewMember, setRenewMember] = useState<Member>(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [toast, setToast] = useState<{type:'success'|'error';message:string}|null>(null);
  const load = useCallback(async () => { try { setError(''); const [p,o,u,m,pl,n,b] = await Promise.all([api<Payment[]>('/payments'),api<Member[]>('/payments/overdue'),api<Payment[]>('/payments/upcoming?days=7'),api<Member[]>('/members'),api<Plan[]>('/plans?onlyActive=true'),api<Member[]>(`/payments/not-renewed?month=${month}`),api<Benefit[]>('/benefits')]); setPayments(p.data);setOverdue(o.data);setUpcoming(u.data);setMembers(m.data);setPlans(pl.data);setNotRenewed(n.data);setBenefits(b.data); } catch(e){setError(e instanceof Error?e.message:'Error');}},[month]);
  useEffect(()=>{load();},[load]);
  const visible = useMemo(()=> (payments||[]).filter(p=>`${p.member?.firstName} ${p.member?.lastName} ${p.member?.dni}`.toLowerCase().includes(query.toLowerCase())),[payments,query]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const body=Object.fromEntries(new FormData(e.currentTarget)); if(!body.expirationDate) delete body.expirationDate; if(!body.amount)delete body.amount; if(!body.appliedBenefitId)delete body.appliedBenefitId; if(!body.paymentDate)delete body.paymentDate; try{await api('/payments',{method:'POST',body:JSON.stringify(body)});setModal(null);setToast({type:'success',message:'Pago registrado correctamente.'});load();}catch(e){setToast({type:'error',message:e instanceof Error?e.message:'Error'});}finally{setSaving(false)}}
  async function renew(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!renewMember)return;setSaving(true);const body = Object.fromEntries(new FormData(e.currentTarget)); if (!body.expirationDate) delete body.expirationDate; if(!body.paymentDate)delete body.paymentDate;try{await api(`/payments/${renewMember.id}/renew`,{method:'POST',body:JSON.stringify(body)});setModal(null);setToast({type:'success',message:'Cuota renovada correctamente.'});load();}catch(e){setToast({type:'error',message:e instanceof Error?e.message:'Error'});}finally{setSaving(false)}}
  async function deletePayment(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (!deleting || !isAdmin) return; setSaving(true);
    try { await api(`/payments/${deleting.id}`, {method:'DELETE'});
      setModal(null); setDeleting(undefined); setToast({type:'success',message:'Pago eliminado. Se actualizaron las cuotas y los totales.'}); await load();
    } catch(e) {setToast({type:'error',message:e instanceof Error?e.message:'No se pudo eliminar el pago'});} finally {setSaving(false);}
  }
  async function updateExpiration(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (!editing) return; setSaving(true);
    try { await api(`/payments/${editing.id}/expiration`, { method: 'PATCH', body: JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))) });
      setModal(null); setToast({type:'success',message:'Vencimiento actualizado.'}); await load();
    } catch (e) { setToast({type:'error',message:e instanceof Error?e.message:'Error'}); } finally {setSaving(false)}
  }
  if(error)return <ErrorState message={error} retry={load}/>;if(!payments)return <Loading/>;
  return <div className="stack"><ToastView toast={toast} clear={()=>setToast(null)}/><div className="toolbar"><div className="tabs"><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>Todos <span>{payments.length}</span></button><button className={tab==='overdue'?'active':''} onClick={()=>setTab('overdue')}>Vencidos <span>{overdue.length}</span></button><button className={tab==='upcoming'?'active':''} onClick={()=>setTab('upcoming')}>Por vencer <span>{upcoming.length}</span></button><button className={tab==='notRenewed'?'active':''} onClick={()=>setTab('notRenewed')}>Sin renovar <span>{notRenewed.length}</span></button>{members.some(m=>m.importKey&&!m.payments.length)&&<button className={tab==='imported'?'active':''} onClick={()=>setTab('imported')}>Importados pendientes <span>{members.filter(m=>m.importKey&&!m.payments.length).length}</span></button>}</div><Button icon={<Plus/>} onClick={()=>{setSelectedPlan('');setPaymentBenefit('');setPaymentAmount('');setPaymentExpiry('');setModal('payment')}}>Registrar pago</Button></div>
    {tab==='all'&&<><div className="search standalone"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar socio en el historial…"/></div><div className="card table-card"><div className="table-scroll"><table><thead><tr><th>Socio</th><th>Plan</th><th>Pago</th><th>Vencimiento</th><th>Método</th><th>Descuento</th><th>Estado</th>{isAdmin&&<th>Acciones</th>}</tr></thead><tbody>{visible.map(p=><tr key={p.id}><td data-label="Socio"><b>{p.member?.firstName} {p.member?.lastName}</b><small>DNI {p.member?.dni}</small></td><td data-label="Plan">{p.plan.name}</td><td data-label="Pago" className="amount">{money(p.finalAmount)}<small>{date(p.paymentDate)}</small></td><td data-label="Vencimiento">{date(p.expirationDate)}</td><td data-label="Método">{paymentMethodLabel(p.paymentMethod)}{p.paymentMethod==='MIXED'&&<small>Efectivo {money(p.cashAmount)} · Transferencia {money(p.transferAmount)}</small>}{p.prorated&&<small>Primer mes proporcional</small>}{Number(p.adjustmentAmount || 0)!==0&&<small>Ajuste sobre tarifa: {money(p.adjustmentAmount)}</small>}</td><td data-label="Descuento">{Number(p.discountPercentage)>0?<span className="tag lime">-{p.discountPercentage}%</span>:'—'}</td><td data-label="Estado"><Status ok={p.status==='PAID'}>{p.status==='PAID'?'Pagado':'Cancelado'}</Status></td>{isAdmin&&<td data-label="Acciones">{p.status==='PAID'&&<Button variant="ghost" onClick={()=>{setEditing(p);setModal('expiration')}}>Editar vencimiento</Button>}<Button variant="danger" onClick={()=>{setDeleting(p);setModal('delete')}}>Eliminar</Button></td>}</tr>)}</tbody></table></div>{!visible.length&&<Empty/>}</div></>}
    {tab==='imported'&&<><p className="muted">Datos del Excel sin pago registrado. Completá plan y beneficio desde Socios; registrá un pago solo con su fecha e importe reales.</p><div className="card-list">{members.filter(m=>m.importKey&&!m.payments.length).map(m=><div className="member-alert" key={m.id}><div className="grow"><b>{m.firstName} {m.lastName}</b><span>{m.currentPlan?.name || 'Plan pendiente'} · Vencimiento del Excel {date(m.importedExpirationDate || undefined)}</span></div><span>{m.dni || 'DNI pendiente'}</span></div>)}</div></>}
    {tab==='overdue' &&<div className="card-list">{overdue.map(m=>{const p=m.payments[0];return <div className="member-alert" key={m.id}><div className="alert-symbol danger"><AlertCircle/></div><div className="grow"><b>{m.firstName} {m.lastName}</b><span>{p?`${p.plan.name} · Venció ${date(p.expirationDate)}`:`Vencimiento del Excel: ${date(memberExpiration(m))}`}</span></div><span>{m.phone}</span>{p&&<Button variant="secondary" onClick={()=>{setRenewMember(m);setModal('renew')}}>Renovar</Button>}</div>})}{!overdue.length&&<Empty title="No hay cuotas vencidas" text="Todos los socios activos están al día."/>}</div>}
    {tab==='upcoming'&&<div className="card-list">{upcoming.map(p=><div className="member-alert" key={p.id}><div className="alert-symbol orange"><CalendarClock/></div><div className="grow"><b>{p.member?.firstName} {p.member?.lastName}</b><span>{p.plan.name} · Vence {date(p.expirationDate)}</span></div><span className="tag orange">{p.daysRemaining} días</span><Button variant="secondary" onClick={()=>{setRenewMember(p.member ? {...p.member,payments:[p]} : undefined);setModal('renew')}}>Renovar</Button></div>)}{!upcoming.length&&<Empty title="Sin vencimientos cercanos" text="No hay cuotas que venzan en los próximos 7 días."/>}</div>}
    {tab==='notRenewed'&&<><Field label="Mes"><input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></Field><p className="muted">Socios activos con pagos anteriores que no registraron un pago durante el mes elegido. La vigencia de su cuota se muestra por separado.</p><div className="card-list">{notRenewed.map(m=><div className="member-alert" key={m.id}><div className="grow"><b>{m.firstName} {m.lastName}</b><span>{m.payments[0]?.plan.name} · Vencimiento {date(m.payments[0]?.expirationDate)}</span></div><span>{m.phone}</span><Button variant="secondary" onClick={()=>{setRenewMember(m);setModal('renew')}}>Renovar</Button></div>)}{!notRenewed.length&&<Empty title="No hay socios sin renovar para este mes"/>}</div></>}
    {isAdmin&&modal==='expiration'&&editing&&<Modal title="Editar vencimiento" subtitle={`${editing.member?.firstName || ''} ${editing.member?.lastName || ''}`} onClose={()=>setModal(null)}><form onSubmit={updateExpiration}><Field label="Fecha de vencimiento *"><input name="expirationDate" type="date" defaultValue={inputDate(editing.expirationDate)} required/></Field><div className="modal-actions"><Button type="button" variant="ghost" onClick={()=>setModal(null)}>Cancelar</Button><Button disabled={saving}>{saving?'Guardando…':'Guardar vencimiento'}</Button></div></form></Modal>}
    {isAdmin&&modal==='delete'&&deleting&&<Modal title="Eliminar pago" subtitle={`${deleting.member?.firstName || ''} ${deleting.member?.lastName || ''}`} onClose={()=>{if(!saving)setModal(null)}}><form onSubmit={deletePayment}>
      <p className="modal-copy">¿Eliminar el pago de {money(deleting.finalAmount)} del {date(deleting.paymentDate)}?</p>
      <p className="modal-copy">Se quitará del historial y de los totales. La vigencia de la cuota se recalculará con los pagos restantes. La acción quedará registrada en auditoría.</p>
      <div className="modal-actions"><Button type="button" variant="ghost" disabled={saving} onClick={()=>setModal(null)}>Cancelar</Button><Button variant="danger" disabled={saving}>{saving?'Eliminando…':'Confirmar eliminación'}</Button></div>
    </form></Modal>}
    {modal==='payment'  &&<Modal title="Registrar pago" subtitle="Creá una nueva cuota para un socio activo." onClose={()=>setModal(null)}><form onSubmit={create}><div className="form-stack"><Field label="Socio *"><select name="memberId" required defaultValue="" onChange={e=>{const m=members.find(m=>m.id===e.target.value);setSelectedPlan(m?.currentPlanId || '');setPaymentBenefit(m?.benefits.find(b=>b.active)?.benefit.id || '');setPaymentExpiry(m?.importedExpirationDate ? inputDate(m.importedExpirationDate) : '');}}><option value="" disabled>Seleccionar socio</option>{members.map(m=><option key={m.id} value={m.id}>{m.firstName} {m.lastName} — {m.dni}</option>)}</select></Field><Field label="Plan *"><select name="planId" required value={selectedPlan} onChange={e=>{setSelectedPlan(e.target.value);setPaymentBenefit('')}}><option value="" disabled>Seleccionar plan</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.price)}</option>)}</select></Field><Field label="Beneficio"><select name="appliedBenefitId" value={paymentBenefit} onChange={e=>setPaymentBenefit(e.target.value)}><option value="">Sin beneficio</option>{benefits.filter(b=>b.active&&(!b.onlyFullPass||plans.find(p=>p.id===selectedPlan)?.name==='Full Pass')).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Fecha de pago" hint="Ingresá la fecha real. Vacío: hoy."><input name="paymentDate" type="date"/></Field><Field label="Importe cobrado" hint="Vacío: precio vigente del plan con el beneficio. Para un pago histórico, ingresá el importe real."><input name="amount" type="number" min="0.01" step="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/></Field><PaymentFields amount={paymentAmount ? Number(paymentAmount) : selectedPlan ? Number(plans.find(p=>p.id===selectedPlan)?.price) * (1-Number(benefits.find(b=>b.id===paymentBenefit)?.discountPercentage || 0)/100) : undefined}/><Field label="Vencimiento" hint="Vacío: 30 días desde la fecha de pago. Para importados se propone el vencimiento del Excel."><input name="expirationDate" type="date" value={paymentExpiry} onChange={e=>setPaymentExpiry(e.target.value)}/></Field></div><div className="form-note"><CheckCircle2/>El backend calcula el monto y valida el beneficio aplicable.</div><div className="modal-actions"><Button type="button" variant="ghost" onClick={()=>setModal(null)}>Cancelar</Button><Button disabled={saving}>{saving?'Guardando…':'Registrar pago'}</Button></div></form></Modal>}
    {modal==='renew'&&renewMember&&<Modal title="Renovar cuota" subtitle={`${renewMember.firstName} ${renewMember.lastName}`} onClose={()=>setModal(null)}><form onSubmit={renew}><Field label="Fecha de pago" hint="Vacío: hoy."><input name="paymentDate" type="date"/></Field><p className="modal-copy">Se renovará el mismo plan y beneficio del último pago. Podés elegir la fecha de vencimiento.</p><PaymentFields amount={renewMember.payments?.[0] ? Number(plans.find(p=>p.id===(renewMember.currentPlanId || renewMember.payments[0].planId))?.price ?? renewMember.payments[0].priceOriginal) * (1 - Number(renewMember.currentPlanId ? renewMember.benefits?.find(b=>b.active)?.benefit.discountPercentage || 0 : renewMember.payments[0].appliedBenefit?.discountPercentage ?? renewMember.payments[0].discountPercentage)/100) : undefined}/><Field label="Vencimiento" hint="Vacío: 30 días desde hoy."><input name="expirationDate" type="date"/></Field><div className="modal-actions"><Button type="button" variant="ghost" onClick={()=>setModal(null)}>Cancelar</Button><Button disabled={saving}>{saving?'Renovando…':'Confirmar renovación'}</Button></div></form></Modal>}
  </div>;
}
