import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { AlertCircle, CalendarClock, CheckCircle2, Plus, Search } from 'lucide-react';
import { api, date, money } from '../api';
import { PaymentFields } from '../payment-fields';
import { inputDate, paymentMethodLabel } from '../payment-utils';
import type { Member, Payment, Plan } from '../types';
import { Button, Empty, ErrorState, Field, Loading, Modal, Status, ToastView } from '../components';

export default function Payments() {
  const [notRenewed, setNotRenewed] = useState<Member[]>([]); const [month, setMonth] = useState(inputDate().slice(0,7));
  const [editing, setEditing] = useState<Payment>(); const [selectedPlan, setSelectedPlan] = useState('');
  const [payments, setPayments] = useState<Payment[]>(); const [overdue, setOverdue] = useState<Member[]>([]); const [upcoming, setUpcoming] = useState<Payment[]>([]); const [members, setMembers] = useState<Member[]>([]); const [plans, setPlans] = useState<Plan[]>([]);
  const [tab, setTab] = useState<'all' | 'overdue' | 'upcoming' | 'notRenewed'>('all'); const [query, setQuery] = useState(''); const [modal, setModal] = useState<'payment' | 'renew' | 'expiration' | null>(null); const [renewMember, setRenewMember] = useState<Member>(); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [toast, setToast] = useState<{type:'success'|'error';message:string}|null>(null);
  const load = useCallback(async () => { try { setError(''); const [p,o,u,m,pl,n] = await Promise.all([api<Payment[]>('/payments'),api<Member[]>('/payments/overdue'),api<Payment[]>('/payments/upcoming?days=7'),api<Member[]>('/members'),api<Plan[]>('/plans?onlyActive=true'),api<Member[]>(`/payments/not-renewed?month=${month}`)]); setPayments(p.data);setOverdue(o.data);setUpcoming(u.data);setMembers(m.data);setPlans(pl.data);setNotRenewed(n.data); } catch(e){setError(e instanceof Error?e.message:'Error');}},[month]);
  useEffect(()=>{load();},[load]);
  const visible = useMemo(()=> (payments||[]).filter(p=>`${p.member?.firstName} ${p.member?.lastName} ${p.member?.dni}`.toLowerCase().includes(query.toLowerCase())),[payments,query]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const body=Object.fromEntries(new FormData(e.currentTarget)); if(!body.expirationDate) delete body.expirationDate; try{await api('/payments',{method:'POST',body:JSON.stringify(body)});setModal(null);setToast({type:'success',message:'Pago registrado correctamente.'});load();}catch(e){setToast({type:'error',message:e instanceof Error?e.message:'Error'});}finally{setSaving(false)}}
  async function renew(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!renewMember)return;setSaving(true);const body = Object.fromEntries(new FormData(e.currentTarget)); if (!body.expirationDate) delete body.expirationDate;try{await api(`/payments/${renewMember.id}/renew`,{method:'POST',body:JSON.stringify(body)});setModal(null);setToast({type:'success',message:'Cuota renovada correctamente.'});load();}catch(e){setToast({type:'error',message:e instanceof Error?e.message:'Error'});}finally{setSaving(false)}}
  async function updateExpiration(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (!editing) return; setSaving(true);
    try { await api(`/payments/${editing.id}/expiration`, { method: 'PATCH', body: JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))) });
      setModal(null); setToast({type:'success',message:'Vencimiento actualizado.'}); await load();
    } catch (e) { setToast({type:'error',message:e instanceof Error?e.message:'Error'}); } finally {setSaving(false)}
  }
  if(error)return <ErrorState message={error} retry={load}/>;if(!payments)return <Loading/>;
  return <div className="stack"><ToastView toast={toast} clear={()=>setToast(null)}/><div className="toolbar"><div className="tabs"><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>Todos <span>{payments.length}</span></button><button className={tab==='overdue'?'active':''} onClick={()=>setTab('overdue')}>Vencidos <span>{overdue.length}</span></button><button className={tab==='upcoming'?'active':''} onClick={()=>setTab('upcoming')}>Por vencer <span>{upcoming.length}</span></button><button className={tab==='notRenewed'?'active':''} onClick={()=>setTab('notRenewed')}>Sin renovar <span>{notRenewed.length}</span></button></div><Button icon={<Plus/>} onClick={()=>{setSelectedPlan('');setModal('payment')}}>Registrar pago</Button></div>
    {tab==='all'&&<><div className="search standalone"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar socio en el historial…"/></div><div className="card table-card"><div className="table-scroll"><table><thead><tr><th>Socio</th><th>Plan</th><th>Pago</th><th>Vencimiento</th><th>Método</th><th>Descuento</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td data-label="Socio"><b>{p.member?.firstName} {p.member?.lastName}</b><small>DNI {p.member?.dni}</small></td><td data-label="Plan">{p.plan.name}</td><td data-label="Pago" className="amount">{money(p.finalAmount)}<small>{date(p.paymentDate)}</small></td><td data-label="Vencimiento">{date(p.expirationDate)}</td><td data-label="Método">{paymentMethodLabel(p.paymentMethod)}{p.paymentMethod==='MIXED'&&<small>Efectivo {money(p.cashAmount)} · Transferencia {money(p.transferAmount)}</small>}{p.prorated&&<small>Primer mes proporcional</small>}</td><td data-label="Descuento">{Number(p.discountPercentage)>0?<span className="tag lime">-{p.discountPercentage}%</span>:'—'}</td><td data-label="Estado"><Status ok={p.status==='PAID'}>{p.status==='PAID'?'Pagado':'Cancelado'}</Status></td><td data-label="Acciones">{p.status==='PAID'&&<Button variant="ghost" onClick={()=>{setEditing(p);setModal('expiration')}}>Editar vencimiento</Button>}</td></tr>)}</tbody></table></div>{!visible.length&&<Empty/>}</div></>}
    {tab==='overdue'&&<div className="card-list">{overdue.map(m=>{const p=m.payments[0];return <div className="member-alert" key={m.id}><div className="alert-symbol danger"><AlertCircle/></div><div className="grow"><b>{m.firstName} {m.lastName}</b><span>{p?`${p.plan.name} · Venció ${date(p.expirationDate)}`:'Sin pagos registrados'}</span></div><span>{m.phone}</span>{p&&<Button variant="secondary" onClick={()=>{setRenewMember(m);setModal('renew')}}>Renovar</Button>}</div>})}{!overdue.length&&<Empty title="No hay cuotas vencidas" text="Todos los socios activos están al día."/>}</div>}
    {tab==='upcoming'&&<div className="card-list">{upcoming.map(p=><div className="member-alert" key={p.id}><div className="alert-symbol orange"><CalendarClock/></div><div className="grow"><b>{p.member?.firstName} {p.member?.lastName}</b><span>{p.plan.name} · Vence {date(p.expirationDate)}</span></div><span className="tag orange">{p.daysRemaining} días</span><Button variant="secondary" onClick={()=>{setRenewMember(p.member ? {...p.member,payments:[p]} : undefined);setModal('renew')}}>Renovar</Button></div>)}{!upcoming.length&&<Empty title="Sin vencimientos cercanos" text="No hay cuotas que venzan en los próximos 7 días."/>}</div>}
    {tab==='notRenewed'&&<><Field label="Mes"><input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></Field><p className="muted">Socios activos con pagos anteriores que no registraron un pago durante el mes elegido. La vigencia de su cuota se muestra por separado.</p><div className="card-list">{notRenewed.map(m=><div className="member-alert" key={m.id}><div className="grow"><b>{m.firstName} {m.lastName}</b><span>{m.payments[0]?.plan.name} · Vencimiento {date(m.payments[0]?.expirationDate)}</span></div><span>{m.phone}</span><Button variant="secondary" onClick={()=>{setRenewMember(m);setModal('renew')}}>Renovar</Button></div>)}{!notRenewed.length&&<Empty title="No hay socios sin renovar para este mes"/>}</div></>}
    {modal==='expiration'&&editing&&<Modal title="Editar vencimiento" subtitle={`${editing.member?.firstName || ''} ${editing.member?.lastName || ''}`} onClose={()=>setModal(null)}><form onSubmit={updateExpiration}><Field label="Fecha de vencimiento *"><input name="expirationDate" type="date" defaultValue={inputDate(editing.expirationDate)} required/></Field><div className="modal-actions"><Button type="button" variant="ghost" onClick={()=>setModal(null)}>Cancelar</Button><Button disabled={saving}>{saving?'Guardando…':'Guardar vencimiento'}</Button></div></form></Modal>}
    {modal==='payment' &&<Modal title="Registrar pago" subtitle="Creá una nueva cuota para un socio activo." onClose={()=>setModal(null)}><form onSubmit={create}><div className="form-stack"><Field label="Socio *"><select name="memberId" required defaultValue=""><option value="" disabled>Seleccionar socio</option>{members.map(m=><option key={m.id} value={m.id}>{m.firstName} {m.lastName} — {m.dni}</option>)}</select></Field><Field label="Plan *"><select name="planId" required value={selectedPlan} onChange={e=>setSelectedPlan(e.target.value)}><option value="" disabled>Seleccionar plan</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.price)}</option>)}</select></Field><PaymentFields amount={selectedPlan ? Number(plans.find(p=>p.id===selectedPlan)?.price) : undefined}/><Field label="Vencimiento" hint="Si lo dejás vacío, se asignan 30 días."><input name="expirationDate" type="date"/></Field></div><div className="form-note"><CheckCircle2/>El backend calcula el monto y valida el beneficio aplicable.</div><div className="modal-actions"><Button type="button" variant="ghost" onClick={()=>setModal(null)}>Cancelar</Button><Button disabled={saving}>{saving?'Guardando…':'Registrar pago'}</Button></div></form></Modal>}
    {modal==='renew'&&renewMember&&<Modal title="Renovar cuota" subtitle={`${renewMember.firstName} ${renewMember.lastName}`} onClose={()=>setModal(null)}><form onSubmit={renew}><p className="modal-copy">Se renovará el mismo plan y beneficio del último pago. Podés elegir la fecha de vencimiento.</p><PaymentFields amount={renewMember.payments?.[0] ? Number(plans.find(p=>p.id===renewMember.payments[0].planId)?.price ?? renewMember.payments[0].priceOriginal) * (1 - Number(renewMember.payments[0].appliedBenefit?.discountPercentage ?? renewMember.payments[0].discountPercentage)/100) : undefined}/><Field label="Vencimiento" hint="Vacío: 30 días desde hoy."><input name="expirationDate" type="date"/></Field><div className="modal-actions"><Button type="button" variant="ghost" onClick={()=>setModal(null)}>Cancelar</Button><Button disabled={saving}>{saving?'Renovando…':'Confirmar renovación'}</Button></div></form></Modal>}
  </div>;
}
